name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)
  
trigger:
  # - main
  - Development

pool:
  name: Azure Pipelines

variables:
  archiveName: 'AP.Prime.UI.zip'
  sandboxName: 'UI'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    Contents: "**"
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(archiveName)'
    replaceExistingArchive: true

# - task: Veracode@3
#   inputs:
#     ConnectionDetailsSelection: 'Endpoint'
#     AnalysisService: 'VeraCodeAPI'
#     veracodeAppProfile: '$(system.teamProject)'
#     version: '$(build.buildNumber)'
#     filepath: '$(Build.ArtifactStagingDirectory)/$(archiveName)'
#     sandboxName: $(sandboxName)
#     createSandBox: true
#     maximumWaitTime: '360'
#     failBuildOnPolicyFail: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'drop'